UIINREACH-202 - remove 'query-string' from dependencies
folio-org/ui-inn-reach pull request #258
Opened 2022-11-03 07:14 UTC by Terala-Priyanka

## Purpose
query-string is incorrectly listed as a peer-dependency
Issue: https://issues.folio.org/browse/UIINREACH-202

2022-11-03 07:23 UTC, Terala-Priyanka commented
@folio-org/fe-tl-reviewers Please review

2022-11-03 12:52 UTC, zburke requested changes
`query-string` needs to move from peer to direct, not be removed altogether. It is still used in  [`src/utils/search-utils.js`](https://github.com/folio-org/ui-inn-reach/blob/e297ef772c38e5459d00ee2d1b3977676086f424/src/utils/search-utils.js#L1) and [`src/hooks/useList.js`](https://github.com/folio-org/ui-inn-reach/blob/e297ef772c38e5459d00ee2d1b3977676086f424/src/hooks/useList.js#L8).

2022-11-04 06:19 UTC, Terala-Priyanka commented
I see that 'query-string' is indirectly available through other dependencies.
Also,
1. All test are in passed status.
2. Made a basic manual sanity test and the functionality seems be working fine.

Hence, instead of moving the package from peer to direct, I have removed it completely.

2022-11-04 13:01 UTC, zburke reviewed
@Terala-Priyanka, the fact that `query-string` is available via hoisting as a side effect of other dependencies is a good point, but it's also irrelevant because other deps' direct-dependencies are considered their private implementation details. `stripes-data-transfer-components` or `stripes-core` etc could be rewritten tomorrow and refactored away from `query-string` or upgraded to an incompatible version of it, and the code here would suddenly stop working. 

IOW, hoisting saves us here, but it's exploiting a loophole, not something we can rely on. yarn agrees and [logs this warning](https://jenkins-aws.indexdata.com/job/Automation/job/build-platform-complete-snapshot/13476/consoleText) when installing deps when building a platform:
```
warning " > @folio/inn-reach@2.0.100000133" has unmet peer dependency "query-string@^5.0.0".
```

I see two options: 
1. argue that `query-string` _should_ be a peer dependency, satisfied as a direct-dep at the platform level, because apps (like ui-inn-reach) and libraries (like `stripes-data-transfer-components`) need to pass instances of it back and forth and therefore need to agree on a common version. 
2. move `query-string` to direct dependency.

2022-11-04 13:32 UTC, Terala-Priyanka commented
Thank you for your review.
I see 'query-string' dependency needs to be platform-level dependency.
May I ask you how and what can be the go forward from here in order to conclude on option1 or option2 for this PR?

2022-11-04 19:56 UTC, zburke commented
It should only be platform-level if apps and libraries pass instances of `query-string` back-and-forth, similar to how, e.g. ui-apps and `stripes-smart-components` need to agree on the `final-form` version because they exchange instances of `Field` imported from `final-form`. Examples of this kind of exchange make the case for option 1. But if it’s just a common (but private) implementation detail of lots of different modules, then option 2 is correct.

We'd need examples of the exchange of a `query-string` object across modules to choose Option 1. Otherwise, for this PR, I think we choose Option 2.

2022-11-07 05:35 UTC, Terala-Priyanka commented
> It should only be platform-level if apps and libraries pass instances of `query-string` back-and-forth, similar to how, e.g. ui-apps and `stripes-smart-components` need to agree on the `final-form` version because they exchange instances of `Field` imported from `final-form`. Examples of this kind of exchange make the case for option 1. But if it’s just a common (but private) implementation detail of lots of different modules, then option 2 is correct.
> 
> We'd need examples of the exchange of a `query-string` object across modules to choose Option 1. Otherwise, for this PR, I think we choose Option 2.

Thank you! I have added "query-string" to direct deps.

2022-11-07 10:44 UTC, zburke approved these changes

2022-11-07 12:41 UTC, mariia-aloshyna approved these changes

2022-11-08 05:34 UTC, merged